sudo: required
language: python
python:
 - "2.7"
before_install:
 - "wget https://www.panda3d.org/download/panda3d-1.8.1/panda3d1.8_1.8.1~precise_amd64.deb"
 - "sudo dpkg -i panda3d1.8_1.8.1~precise_amd64.deb"
 - "sudo apt-get -f install"
install: true
script: "python pandaplant/demo.py"
